# Generated by Django 3.1.7 on 2021-04-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting_system', '0004_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
