# Generated by Django 3.1.7 on 2021-04-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulting_system', '0005_delete_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('a1', models.FloatField()),
                ('a2', models.FloatField()),
                ('a3', models.FloatField()),
                ('a4', models.FloatField()),
                ('a5', models.FloatField()),
                ('a6', models.FloatField()),
                ('a7', models.FloatField()),
                ('a8', models.FloatField()),
                ('a9', models.FloatField()),
                ('a10', models.FloatField()),
            ],
        ),
    ]
