# Generated by Django 3.1.7 on 2021-03-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_val',
            field=models.IntegerField(default=2, null=True, verbose_name='choice_val'),
        ),
    ]
