# Generated by Django 3.1.7 on 2021-03-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choice_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(default='', max_length=15000),
        ),
    ]
